version: '3.8'

services: # <-- CLAVE: Los tres servicios deben estar aquí debajo, al mismo nivel de indentación.
  
  # === SERVICIO DE BASE DE DATOS (DB) ===
  db:
    image: postgres:16-alpine
    container_name: db_federici
    
    environment:
      POSTGRES_USER: jnegrete
      POSTGRES_PASSWORD: IntiMayu
      POSTGRES_DB: federici
      
    volumes:
      - db_data:/var/lib/postgresql/data
      
    ports:
      - "5432:5432"
      
    restart: always
 
  # === SERVICIO DE BACKEND (FASTAPI) ===
  backend:
    # Construye a partir del Dockerfile que está en la carpeta 'backend'
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_federici # Nombre del contenedor backend
      
    # Mapea los puertos
    ports:
      - "8000:8000"
      
    # Variables de entorno CLAVE para que el código Python sepa cómo conectar a la DB
    environment:
      DB_HOST: db # CLAVE: Este es el nombre del servicio de DB en Docker Compose
      DB_NAME: federici
      DB_USER: jnegrete
      DB_PASS: IntiMayu
      DB_PORT: 5432

    # CLAVE: Comando de inicio explícito con --reload para desarrollo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    # Montaje de volumen para desarrollo
    volumes:
      # CORRECCIÓN: Ahora mapea el código local a /app/backend, que es el WORKDIR en el Dockerfile.
      - ./backend:/app/backend
      
    # Asegura que la DB esté lista antes de que el backend intente conectar
    depends_on:
      - db
      
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile 
    container_name: op_frontend
    restart: always
    # === LA CORRECCIÓN CLAVE: 5173 del Host va al 5173 del Contenedor (donde corre Vite) ===
    ports:
      - "5173:5173" 
    volumes:
      # Monta el código fuente para el hot-reload de React/Vite
      - ./frontend:/app
      # Evita que node_modules se sobreescriba desde el host
      - /app/node_modules
    depends_on:
      - backend



# === VOLÚMENES PERSISTENTES ===
volumes:
  db_data:
